config/routes.rb
Rails.application.routes.draw do

      root 'pages#home'
      get 'about' => 'pages#about'
      get 'test' => 'pages#test'
      get 'signup' => 'users#new'
      get 'login' => 'sessions#new'
      post 'login' => 'sessions#create'
      delete 'logout' => 'sessions#destroy'
      resources :users, except: [:new]
      resources :articles
      resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3, maximum: 30}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates:user_id, presence: true
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, uniqueness: {case_sensitive: false},
  length: {minimum: 3, maximum: 25}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  has_secure_password
  before_save { self.email = email.downcase }
  validates :username, presence: true, 
            length: {minimum: 3, maximum: 16}, 
            uniqueness: {case_sensitive: false}
  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
            uniqueness: {case_sensitive: false},
            length: {maximum: 105}, format:{with: VALID_EMAIL_REGEX} 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to pergorm that action"
      redirect_to root_path
    end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:edit, :show, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @article = Article.new
  end
  
  def create
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render :new
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render :edit
    end
  end
  
  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end
  
  private
  
    def set_article
      @article = Article.find(params[:id])
    end
  
    def article_params
      params.require(:article).permit(:title, :description)
    end
  
    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:danger] = "You can only edit or delete your own articles"
        redirect_to root_path
      end
    end
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    
  end
  
  def show
    
  end
  
  def new
    
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
  
  def test
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin_user, only: [:destroy]
  
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "User was successfully updated"
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "The user and all articles created by him/her have been deleted"
    redirect_to users_path
  end
    
  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end
  
  #=====================================
  
  private
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  
  def require_same_user
    if !logged_in? || (current_user != @user && !current_user.admin?)
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end
  
  def require_admin_user
    if !logged_in? || !current_user.admin?
      flash[:danger] = "Only admins can delete users"
      redirect_to root_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
  end
end

app/views/articles/_form.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-md-8 ml-md-auto mr-md-auto">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">
            <%=link_to article.title, article_path(article)%>
          </h4>
          <div class="card-text">
            <%= truncate(article.description, length: 100) %>
            <div class="article_meta_data">
              <small>
                Created by: <%= article.user.username if article.user %>,
                <%= time_ago_in_words(article.created_at) %> ago,
                last updated: <%= time_ago_in_words(article.updated_at) %> ago 
              </small>
            </div>
          </div>
        </div>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="card-footer">
            <%=link_to "Edit this article", edit_article_path(article), class: "btn btn-primary btn-sm" %>
            <%=link_to "Delete this article", article_path(article), class: "btn btn-danger btn-sm", method: :delete, data: {confirm: "Are you sure?"}%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1 align="center" class="edit-title">Edit existing article</h1>
<%= render 'layouts/errors', obj: @article, cname: "article", opType: "edited" %>
<%= render 'layouts/form' %>

app/views/articles/index.html.erb
<h1 align="center" class="list-title">Listing all articles</h1>
<%= will_paginate %>
<%= render 'form', obj: @articles %>
<%= will_paginate %>

app/views/articles/new.erb
<h1>Create an article</h1>
<% if @article.errors.any? %>
  <h3>The following errors prevented the article from being created</h3>
  <ul>
  <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>
<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %></br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %></br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<%end%>

app/views/articles/new.html.erb
<h1 align="center" class="create-title">Create an article</h1>
<%= render 'layouts/errors', obj: @article, cname: "article", opType: "created" %>
<%= render 'layouts/form' %>

app/views/articles/show.html.erb
<h2 align="center" class="show-title">Title:  <%= @article.title %></h2>
<div class="col-md-8 ml-md-auto mr-md-auto">
  <div class="card center">
    <div class="card-body">
      <% if @article.user %>
        <div class="card-block">
          <%= link_to gravatar_for(@article.user), user_path(@article.user), class: "card-img-top" %>
        </div>
        <div class="card-block">
          <%= link_to @article.user.username, user_path(@article.user), class: "card-link font-weight-bold" %>
        </div>
        <div class="card-block">
          <small><%= pluralize(@article.user.articles.count, "article") %></small>
        </div>
      <% end %>
      <h4 class="card-title center">
        Description
      </h4>
      <hr>
      <p class="card-text">
        <%= @article.description %>
      </p>
    </div>
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <div class="card-footer">
        <%=link_to "Edit this article", edit_article_path(@article), class: "btn btn-primary btn-sm" %>
        <%=link_to "Delete this article", article_path(@article), class: "btn btn-danger btn-sm", method: :delete, data: {confirm: "Are you sure?"}%>
        <%=link_to "View all articles", articles_path, class: "btn btn-success btn-sm" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="col-md-8">
      <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">
          <%= pluralize(obj.errors.count, "error") %> prevented the <%= cname %> from being <%= opType %>
        </h4>
        <ul>
          <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; Made by <a href="https://github.com/mohamed-elmahdi">Mohamed El-Mahdi</a>
    </small>
    <nav>
      <ul>
        <li><%=link_to "About", about_path%></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_form.html.erb
<div class='row'>
  <div class= 'col-sm-12'>
    <%= form_for @article do |f| %>
      <div class="form-group">
        <div class="col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class:"form-control", placeholder: "Title of article", autofocus: true  %>
        </div>
      </div>
      <!--<div class="col-5" style="background-color: blue">fgdf</div>
      <div class="col-5" style="background-color: red"> dsfsd</div>-->
      <div class="form-group">
        <div class="col">
        <%= f.label :description %>
        </div>
        <div class= "col-sm-8">
        <%= f.text_area :description, class:"form-control", rows: 10, placeholder: "Description" %>
        </div>
      </div>
      <div class="col create-btn update-btn">
        <%= f.submit class: "btn btn-danger btn-lg"%>
      </div>
    <%end%>
    <div class="col-sm-4 ml-sm-auto mr-sm-auto">
      [ <%=link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-10 mr-md-auto ml-md-auto">
    <% flash.each do |key, value| %>
      <div class='alert alert-<%="#{key}"%> alert-dismissible fade show' role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= value %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %> 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "New Article", new_article_path, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if logged_in? %>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Your Profile <% if current_user.admin? %> <small>Admin</small> <% end %>
            </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %></br>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<html>
  <head>
    <title>
      About
    </title>
  </head>
  <body>
    <p>This is the about page</p>
    <%= link_to 'Home', root_path %>
  </body>
</html>

app/views/pages/home.html.erb
<html>
  <head>
    <title>
      Home
    </title>
  </head>
  <body>
    <div class="center jumbotron">
      <h1 class="display-1">Alpha</br>Blog</h1>
      <p class="lead">
        <%= link_to "Sign up now", signup_path, class: 'sign-up btn btn-primary btn-lg'%>
      </p>
    </div>
  </body>
</html>

app/views/pages/test.html.erb
<div class="card text-center">
  <div class="card-header">
    Featured
  </div>
  <div class="card-body">
    <h4 class="card-title">Special title treatment</h4>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
  <div class="card-footer text-muted">
    2 days ago
  </div>
</div>

app/views/users/_form.html.erb
<div class='row'>
  <div class= 'col-sm-12'>
    <%= form_for @user do |f| %>
      <div class="form-group">
        <div class="col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :username, class:"form-control", placeholder: "Enter your username", autofocus: true  %>
        </div>
      </div>
      <!--<div class="col-5" style="background-color: blue">fgdf</div>
      <div class="col-5" style="background-color: red"> dsfsd</div>-->
      <div class="form-group">
        <div class="col">
        <%= f.label :email %>
        </div>
        <div class= "col-sm-8">
        <%= f.text_field :email, class:"form-control", placeholder: "Enter your email" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col">
        <%= f.label :password %>
        </div>
        <div class= "col-sm-8">
        <%= f.password_field :password, class:"form-control", placeholder: "Enter your password" %>
        </div>
      </div>
      <div class="col create-btn update-btn">
        <%= f.submit @user.new_record? ? "Sign up" : "Update account", class: "btn btn-danger btn-lg" %>
      </div>
    <%end%>
    <div class="col-sm-4 ml-sm-auto mr-sm-auto">
      [ <%=link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 align="center" class="edit-title">Edit your account</h1>
<%= render 'layouts/errors', obj: @user, cname: "user", opType: "created" %>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center" class="user-title">All Alpha Bloggers</h1>
<%= will_paginate %>
<% @users.each do |user| %>
  <div class="row center">
    <div class="col-md-5 mx-auto card user-card">
      <div class="card-block">
        <%= link_to gravatar_for(user), user_path(user), class: "card-img-top" %>
      </div>
      <div class="card-block">
        <%= link_to user.username, user_path(user), class: "card-link font-weight-bold" %>
      </div>
      <div class="card-block">
        <small><%= pluralize(user.articles.count, "article") %></small>
      </div>
      <% if current_user && current_user.admin? %>
        <div>
          <%= link_to "Delete this user", user_path(user), method: :delete,
          data: {confirm: "Are you sure you want to delete this user and all his/her articles"} %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
<%= will_paginate %>

app/views/users/new.html.erb
<h1 align="center" class="edit-title">Sign up for Alpha Blog</h1>
<%= render 'layouts/errors', obj: @user, cname: "user", opType: "created" %>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center" class="user-title">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
  <div class="col-md-4 ml-md-auto mr-md-auto center">
    <%= gravatar_for @user %>
  </div>
</div>
<h4 align="center" class="user-title"><%= @user.username %>'s articles</h4>
<%= will_paginate @articles%>
<%= render 'articles/form', obj: @articles %>
<%= will_paginate @articles%>